name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write
  attestations: write

jobs:
  release-please:
    name: Release please a new version
    runs-on: ubuntu-22.04
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          skip-labeling: true
